name: lylme_spage
build:
  dockerfile: ./php/Dockerfile
services:
  - type: web
    name: spage-web
    env: docker
    dockerfilePath: ./php/Dockerfile
    envVars:
      - key: TZ
        value: Asia/Shanghai
    ports:
      - "8080:80"
  - type: database
    name: spage-db
    env: docker
    dockerImage: mysql:5.7
    envVars:
      - key: TZ
        value: Asia/Shanghai
      - key: MYSQL_ROOT_PASSWORD
        value: 123456
      - key: MYSQL_DATABASE
        value: spage
    port: 3306
    numInstances: 1
